site_name: Lineblock
site_description: Test code examples
site_url: https://lineblock.org/

repo_name: kimjarvis/lineblock
repo_url: https://github.com/kimjarvis/lineblock

theme:
  name: material
  palette:
    scheme: slate  # This enables dark mode with no toggle

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Use cases: index.md
  - Tutorial: tutorial.md
  - Development:
      - Parse Parentheses: parse_parentheses.md
      - Ensure Balanced Parentheses: ensure_balanced_parentheses.md
      - Isolate Blocks: isolate_blocks.md
      - Process Chunks: process_chunks.md


